import type { ProductAttrs } from "../models/Product";

type SeedProduct = Omit<ProductAttrs, "createdAt" | "updatedAt" | "images" | "active" | "color2"> & {
  color2?: string;
};

/**
 * The ten sets from the design prototype. Names, colours, shapes, finishes and copy are as designed.
 * PLACEHOLDER: every pricePaise and stock value below is a stand-in until the owner confirms real figures.
 */
export const SEED_PRODUCTS: SeedProduct[] = [
  {
    slug: "blush-hour",
    name: "Blush Hour",
    shape: "almond",
    finish: "ombre",
    occasion: "everyday",
    color: "#E8B2AA",
    color2: "#F7E4DF",
    pricePaise: 119900,
    stock: 20,
    sortOrder: 10,
    description: "A soft sunrise fade from milk to petal. Goes with everything and shows growth gracefully.",
  },
  {
    slug: "noir-gloss",
    name: "Noir Gloss",
    shape: "coffin",
    finish: "gloss",
    occasion: "party",
    color: "#241E1F",
    pricePaise: 129900,
    stock: 20,
    sortOrder: 20,
    description: "Deep black with a mirror shine. Sharp coffin tips for nights out.",
  },
  {
    slug: "gold-leaf-french",
    name: "Gold Leaf French",
    shape: "almond",
    finish: "french",
    occasion: "bridal",
    color: "#EBCFC4",
    pricePaise: 159900,
    stock: 20,
    sortOrder: 30,
    description: "A classic French tip on a sheer blush base, finished with a gold line.",
  },
  {
    slug: "rose-chrome",
    name: "Rose Chrome",
    shape: "almond",
    finish: "chrome",
    occasion: "party",
    color: "#D49C8B",
    pricePaise: 149900,
    stock: 20,
    sortOrder: 40,
    description: "Liquid rose-gold chrome that moves with the light.",
  },
  {
    slug: "garnet-cat-eye",
    name: "Garnet Cat-Eye",
    shape: "stiletto",
    finish: "cateye",
    occasion: "party",
    color: "#8A2E41",
    pricePaise: 139900,
    stock: 20,
    sortOrder: 50,
    description: "A magnetic garnet streak that shifts as your hand moves.",
  },
  {
    slug: "milk-bath",
    name: "Milk Bath",
    shape: "oval",
    finish: "gloss",
    occasion: "everyday",
    color: "#EFE6DB",
    pricePaise: 89900,
    stock: 20,
    sortOrder: 60,
    description: "Sheer, creamy and clean. The easiest set to wear to work.",
  },
  {
    slug: "pearl-veil",
    name: "Pearl Veil",
    shape: "coffin",
    finish: "glitter",
    occasion: "bridal",
    color: "#EDE6EA",
    pricePaise: 189900,
    stock: 20,
    sortOrder: 70,
    description: "Pearl base scattered with fine glitter. Made for wedding week.",
  },
  {
    slug: "mocha-matte",
    name: "Mocha Matte",
    shape: "square",
    finish: "matte",
    occasion: "everyday",
    color: "#8F6E5F",
    pricePaise: 99900,
    stock: 20,
    sortOrder: 80,
    description: "A velvet matte in warm cocoa, with a short square shape.",
  },
  {
    slug: "sage-line-art",
    name: "Sage Line Art",
    shape: "oval",
    finish: "art",
    occasion: "everyday",
    color: "#CBD3C0",
    pricePaise: 129900,
    stock: 20,
    sortOrder: 90,
    description: "Muted sage with a single gold line drawn across each nail.",
  },
  {
    slug: "midnight-foil",
    name: "Midnight Foil",
    shape: "stiletto",
    finish: "chrome",
    occasion: "party",
    color: "#3A4A7C",
    pricePaise: 169900,
    stock: 20,
    sortOrder: 100,
    description: "Inky blue foil with a long stiletto shape and a cold shine.",
  },
];
